sudo: false
dist: xenial
language: node_js
node_js: 8.11

before_install:
  - "sudo apt-get -qq update"
  - "sudo apt-get install -y matchbox-window-manager"

install:
  - matchbox-window-manager&
  - sleep 5

services:
  - xvfb

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  chrome: stable

jobs:
  include:
    - if: type = push
      env: TEST_SUITE=mobile POLYMER=2
    - if: type = push
      env: TEST_SUITE=desktop POLYMER=2
    - if: type = push
      env: TEST_SUITE=visual_tests POLYMER=2
    - if: type = push
      env: TEST_SUITE=mobile POLYMER=3
    - if: type = push
      env: TEST_SUITE=desktop POLYMER=3
    - if: type = pull_request
      env: POLYMER=2
    - if: type = pull_request
      env: POLYMER=3
    - if: type = cron
      env: TEST_SUITE=unit_tests POLYMER=2

script:
  - if [[ "$POLYMER" = "2" ]]; then
      npm -q i && npm i -q --no-save bower polymer-cli && bower -q i &&
      if [[ "$TRAVIS_EVENT_TYPE" = "pull_request" ]]; then
        npm run check &&
        npm run lint &&
        wct;
      elif [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then
        wct --env saucelabs-cron;
      elif [[ "$TEST_SUITE" = "visual_tests" ]]; then
        npm i -q --no-save gemini@^4.0.0 gemini-sauce gemini-polyserve &&
        gemini test test/visual;
      else
        wct --env saucelabs:$TEST_SUITE;
      fi;
    fi
  - if [[ "$POLYMER" = "3" ]]; then
      npm --no-save -q install -g yarn bower magi-cli web-component-tester polymer-modulizer &&
      rm -rf node_modules &&
      magi p3-convert --out . --import-style=name &&
      yarn install --flat &&
      if [[ "$TRAVIS_EVENT_TYPE" = "pull_request" ]]; then
        wct --npm;
      else
        wct --npm --env saucelabs:$TEST_SUITE;
      fi;
    fi

after_success:
  - "cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls"
